source "https://rubygems.org"

gem "sinatra", :require => "sinatra/base"
gem "pivotal-tracker"
gem "json"
gem "shotgun"
gem "sinatra-backbone", :require => "sinatra/backbone"
gem "jammit-sinatra"
gem "sinatra-respond_to", :require => "sinatra/respond_to"
gem "padrino-helpers", :require => "padrino-helpers"